
export enum ModalConstant {
    addUserModal = "AddUserModal",
    viewUserDetailsModal="ViewUserDetailsModal",
    editUserModal="EditUserModal",
    notificationModal="NotificationModal",
    createAppCanvasModal="CreateAppCanvasModal",
    createApiModal="CreateApiModal",
    addApplicationModal="AddApplicationModal",
    updateApiModal="UpdateApiModal",
    createSupportTicketModal="CreateSupportTicketModal",
    updateSupportTicketModal="UpdateSupportTicketModal",
    confirmationModal="ConfirmationModal",
    updateUserModal="UpdateUserModal",
    createMenuModal="CreateMenuModal",
    createMenuStepModal="CreateMenuStepModal",
    declineCheckerModal="DeclineCheckerModal",
    viewApiDetailsModal="ViewApiDetailsModal",
    updateMenuModal="UpdateMenuModal",
    loginRequestModal="LoginRequestModal",
    submitApplicationModal="SubmitApplicationModal",
    publishApplicationModal="PublishApplicationModal",
    leavingPageModal="LeavingPageModal",
    updateMenuStepModal="UpdateMenuStepModal",
    addAggregatorModal="AddAggregatorModal",
}
